### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by derhuerst** [derhuerst/poodle-to-poodle#1]
- [x] validate user input
- [ ] tool to generate a dat archive containing the app
- [ ] UI for sync status: peers, last known revision, etc
- [ ] deploy to hashbase
- [ ] a nice tutorial on how to get it running in [beaker browser](https://beakerbrowser.com)
- [ ] display errors in the UI
- [ ] provide a link to share
- [ ] use [WebDB](https://github.com/beakerbrowser/webdb) – #6
- [ ] consider [JSON-LZ](https://github.com/pfrazee/json-lz) for the votes markup

**Comment by dirkschumacher** [comment]
🐩⼆🐩

**Comment by dirkschumacher** [comment]
But most importantly, find a way that non dat archive owners can make commits to the archive.

**Comment by dirkschumacher** [comment]
One possible flow could be:

* Alice creates a new poll and gets redirected to the poll's dat URL (`url:a`)
* Alice updates her availability and sends the dat URL (`url:a`) to Bob by some communication medium
* Bob forks the archive (`url:a` => `url:b`) and updates his availability. He then sends the url to Alice (`url:b`)
* Alice goes back to her website at `url:a` and clicks on "sync" and enters Bob's website (`url:b`). 
* `url:a` now holds the most recent state.

**Comment by derhuerst** [comment]
While this seems to be the most elegant way given the single-writer nature of dat, it might be easier to wait for multi-writer support. I'll try to ask someone how long this will take.

**Comment by derhuerst** [comment]
> I'll try to ask someone how long this will take.

Unfortunately 'soon' means "it's a priority but we don't know when."

**Comment by dirkschumacher** [comment]
@derhuerst Maybe we should implement it using the flow outlined above and then change it once multi-writes are available

**Comment by derhuerst** [comment]
There are many relatively well-known sites/apps on top of beaker now that follow the forking pattern.
